package journal

import (
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

// The quota includes current files, archives and accepted buffered bytes.
// It covers canonical journal files, not unrelated files or external writers.
const DefaultMaxDiskSize int64 = 1 << 30
const DefaultMaxDiskFiles = 8192
const maxRetentionDirectoryEntries = 16384

var errRetentionBusy = errors.New("journal retention is busy; retry after storage work completes")
var errDiskCapacity = errors.New("journal disk quota exhausted; no removable historical journal")

type diskFile struct {
	unit     string
	size     int64
	modified time.Time
}

type diskRetention struct {
	ready   bool
	files   map[string]diskFile
	bytes   int64
	err     error
	retryAt time.Time
}

// Only the reversible names generated by the journal and its three archive
// generations belong to the retention namespace. Unknown files are untouched.
func retainedDiskName(name string) (string, bool) {
	base := name
	if !strings.HasSuffix(base, ".log") {
		found := false
		for i := 1; i <= DefaultKeep; i++ {
			if b, ok := strings.CutSuffix(name, "."+strconv.Itoa(i)); ok {
				base, found = b, true
				break
			}
		}
		if !found {
			return "", false
		}
	}
	unit, ok := decodeUnitFileName(base)
	// Empty unit names are never written; the literal standalone name owns
	// this historical fallback spelling. Dot-only aliases are rejected on open.
	if base == "_unknown.log" {
		unit = "_unknown"
	}
	return unit, ok && unit != "" && unitFileName(unit) == base
}

// Initial indexing is lazy so a malformed/full directory leaves control and
// loss diagnostics available. One caller owns bounded enumeration; concurrent
// callers fail visibly rather than adding workers or waiting under store locks.
func (s *Store) initializeDisk() error {
	s.diskMu.Lock()
	ready, err, retry := s.disk.ready, s.disk.err, s.disk.retryAt
	s.diskMu.Unlock()
	if ready {
		return nil
	}
	if err != nil && time.Now().Before(retry) {
		return err
	}
	select {
	case s.diskGate <- struct{}{}:
	default:
		return errRetentionBusy
	}
	defer func() { <-s.diskGate }()
	s.diskMu.Lock()
	ready, err, retry = s.disk.ready, s.disk.err, s.disk.retryAt
	s.diskMu.Unlock()
	if ready {
		return nil
	}
	if err != nil && time.Now().Before(retry) {
		return err
	}
	files, size, err := s.scanDisk()
	s.diskMu.Lock()
	defer s.diskMu.Unlock()
	if err != nil {
		s.disk.err, s.disk.retryAt = err, time.Now().Add(time.Second)
		return err
	}
	s.disk = diskRetention{ready: true, files: files, bytes: size}
	return nil
}

func (s *Store) scanDisk() (map[string]diskFile, int64, error) {
	root, err := os.OpenRoot(s.dir)
	if err != nil {
		return nil, 0, err
	}
	defer root.Close()
	dir, err := root.Open(".")
	if err != nil {
		return nil, 0, err
	}
	defer dir.Close()
	files := make(map[string]diskFile)
	var bytes int64
	count := 0
	for {
		entries, readErr := dir.ReadDir(256)
		for _, entry := range entries {
			count++
			if count > maxRetentionDirectoryEntries {
				return nil, 0, errors.New("journal retention directory exceeds 16384 entries; remove unrelated or excess history and retry")
			}
			unit, owned := retainedDiskName(entry.Name())
			if !owned {
				continue
			}
			if len(files) >= DefaultMaxDiskFiles {
				return nil, 0, errors.New("journal history index exceeds 8192 files; remove excess history and retry")
			}
			info, err := root.Lstat(entry.Name())
			if os.IsNotExist(err) {
				continue
			}
			if err != nil {
				return nil, 0, err
			}
			if !info.Mode().IsRegular() {
				return nil, 0, fmt.Errorf("journal retention rejects nonregular file %q", entry.Name())
			}
			if info.Size() < 0 || info.Size() > int64(^uint64(0)>>1)-bytes {
				return nil, 0, errors.New("journal history size overflow")
			}
			files[entry.Name()] = diskFile{unit: unit, size: info.Size(), modified: info.ModTime()}
			bytes += info.Size()
		}
		if errors.Is(readErr, io.EOF) {
			break
		}
		if readErr != nil {
			return nil, 0, readErr
		}
	}
	return files, bytes, nil
}

func (s *Store) diskLimits() (int64, int) {
	bytes, files := s.maxDiskSize, s.maxDiskFiles
	if bytes <= 0 {
		bytes = DefaultMaxDiskSize
	}
	if files <= 0 || files > DefaultMaxDiskFiles {
		files = DefaultMaxDiskFiles
	}
	return bytes, files
}

// reserveDisk runs under the writing unit's lock. No journal/coordinator/queue
// metadata lock is held during indexing or deletion. Buffered bytes count now,
// so independent timer flushes cannot overrun the accepted byte budget later.
func (s *Store) reserveDisk(unit string, bytes int64, opening bool) error {
	if err := s.initializeDisk(); err != nil {
		return err
	}
	maxBytes, maxFiles := s.diskLimits()
	if bytes < 0 || bytes > maxBytes {
		return errDiskCapacity
	}
	name := unitFileName(unit)
	for attempts := 0; attempts <= DefaultMaxDiskFiles; attempts++ {
		s.diskMu.Lock()
		file, exists := s.disk.files[name]
		if !exists && !opening {
			s.diskMu.Unlock()
			return errors.New("journal disk reservation has no current file")
		}
		if s.disk.bytes <= maxBytes-bytes && (exists || len(s.disk.files) < maxFiles) {
			file.unit, file.modified = unit, time.Now()
			file.size += bytes
			s.disk.files[name] = file
			s.disk.bytes += bytes
			s.diskMu.Unlock()
			return nil
		}
		s.diskMu.Unlock()
		if err := s.pruneHistoricalDisk(unit); err != nil {
			return err
		}
	}
	return errDiskCapacity
}

func (s *Store) releaseDisk(unit string, bytes int64) {
	s.diskMu.Lock()
	defer s.diskMu.Unlock()
	name := unitFileName(unit)
	f := s.disk.files[name]
	f.size -= bytes
	s.disk.bytes -= bytes
	s.disk.files[name] = f
}

func (s *Store) observeDisk(unit string, size int64) {
	s.diskMu.Lock()
	defer s.diskMu.Unlock()
	name := unitFileName(unit)
	f := s.disk.files[name]
	s.disk.bytes += size - f.size
	f.size, f.unit, f.modified = size, unit, time.Now()
	s.disk.files[name] = f
}

func (s *Store) forgetDiskLocked(name string) {
	s.disk.bytes -= s.disk.files[name].size
	delete(s.disk.files, name)
}

// Apply each completed native rotation step once, including missing sources.
// Failed native operations preserve both accounting and retry ownership.
func (s *Store) rotatedDisk(unit string, step, keep int, moved bool) {
	base := unitFileName(unit)
	from := base
	if step > 0 {
		from += "." + strconv.Itoa(step)
	}
	s.diskMu.Lock()
	defer s.diskMu.Unlock()
	file, exists := s.disk.files[from]
	s.forgetDiskLocked(from)
	if step == keep || !moved {
		return
	}
	to := base + "." + strconv.Itoa(step+1)
	s.forgetDiskLocked(to)
	if exists {
		s.disk.files[to] = file
		s.disk.bytes += file.size
	}
}

// A historical unit has no open/failed file owner. Reserve its name under mu
// before native removal, so a new capture cannot race deletion. No unit lock is
// acquired here: a blocked deletion cannot block another unit's Sync/retirement.
func (s *Store) pruneHistoricalDisk(exclude string) error {
	select {
	case s.diskGate <- struct{}{}:
	default:
		return errRetentionBusy
	}
	defer func() { <-s.diskGate }()
	s.mu.Lock()
	s.diskMu.Lock()
	unit := ""
	var oldest time.Time
	recent := make(map[string]time.Time)
	for _, f := range s.disk.files {
		if f.unit == exclude || s.files[f.unit] != nil || s.pruning[f.unit] {
			continue
		}
		if prior, ok := recent[f.unit]; !ok || f.modified.After(prior) {
			recent[f.unit] = f.modified
		}
	}
	for candidate, modified := range recent {
		if unit == "" || modified.Before(oldest) || modified.Equal(oldest) && candidate < unit {
			unit, oldest = candidate, modified
		}
	}
	if unit == "" {
		s.diskMu.Unlock()
		s.mu.Unlock()
		return errDiskCapacity
	}
	names := make([]string, 0, DefaultKeep+1)
	for name, f := range s.disk.files {
		if f.unit == unit {
			names = append(names, name)
		}
	}
	s.pruning[unit] = true
	s.diskMu.Unlock()
	s.mu.Unlock()
	defer func() { s.mu.Lock(); delete(s.pruning, unit); s.mu.Unlock() }()
	sort.Strings(names)
	root, err := os.OpenRoot(s.dir)
	if err != nil {
		return err
	}
	defer root.Close()
	for _, name := range names {
		info, err := root.Lstat(name)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if err == nil {
			if !info.Mode().IsRegular() {
				return fmt.Errorf("journal retention rejects nonregular file %q", name)
			}
			if s.onRetentionRemove != nil {
				err = s.onRetentionRemove(name)
			}
			if err == nil {
				err = root.Remove(name)
			}
			if err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("remove historical journal: %w", err)
			}
		}
		s.diskMu.Lock()
		s.forgetDiskLocked(name)
		s.diskMu.Unlock()
		if info != nil && err == nil {
			s.queueMu.Lock()
			s.addStatsLocked(unit, CaptureStats{EvictedFiles: 1, EvictedBytes: uint64(info.Size())})
			s.queueMu.Unlock()
		}
	}
	return nil
}
